export const colorEffects = [
  { name: 'None', value: 'none' },
  { name: 'Sepia', value: 'sepia(100%)' },
  { name: 'Grayscale', value: 'grayscale(100%)' },
  { name: 'Vintage', value: 'sepia(50%) contrast(110%) brightness(110%) saturate(90%)' },
  { name: 'Cool', value: 'hue-rotate(180deg) saturate(120%)' },
  { name: 'Warm', value: 'sepia(30%) saturate(140%) hue-rotate(-10deg)' },
  { name: 'Dramatic', value: 'contrast(150%) brightness(90%)' },
  { name: 'Noir', value: 'grayscale(100%) contrast(120%) brightness(90%)' },
  { name: 'Fade', value: 'opacity(90%) brightness(110%)' },
  { name: 'Vivid', value: 'saturate(150%) contrast(110%)' },
  { name: 'Retro', value: 'sepia(40%) saturate(120%) hue-rotate(-20deg)' },
  { name: 'Muted', value: 'saturate(80%) brightness(105%)' },
  { name: 'Cinematic', value: 'contrast(110%) brightness(95%) saturate(110%)' },
  { name: 'Summer', value: 'brightness(110%) saturate(130%) hue-rotate(20deg)' },
  { name: 'Winter', value: 'brightness(100%) saturate(90%) hue-rotate(180deg)' },
  { name: 'Forest', value: 'hue-rotate(60deg) saturate(120%) brightness(95%)' },
  { name: 'Ocean', value: 'hue-rotate(180deg) saturate(110%) brightness(105%)' },
  { name: 'Sunset', value: 'sepia(30%) saturate(140%) hue-rotate(-20deg) brightness(110%)' },
  { name: 'Neon', value: 'brightness(110%) contrast(120%) saturate(150%)' },
  { name: 'Pastel', value: 'brightness(110%) saturate(70%)' },
  { name: 'Polaroid', value: 'sepia(20%) saturate(90%) contrast(110%) brightness(110%)' },
  { name: 'Chrome', value: 'contrast(120%) saturate(110%) brightness(110%)' },
  { name: 'Mono', value: 'grayscale(100%) contrast(110%)' },
  { name: 'Infrared', value: 'hue-rotate(180deg) saturate(200%) contrast(120%)' },
  { name: 'Twilight', value: 'brightness(90%) sepia(30%) hue-rotate(200deg)' },
  { name: 'Ember', value: 'sepia(50%) saturate(140%) hue-rotate(-30deg)' },
  { name: 'Arctic', value: 'brightness(110%) saturate(80%) hue-rotate(180deg)' },
  { name: 'Desert', value: 'sepia(40%) saturate(130%) brightness(110%)' },
  { name: 'Cosmic', value: 'hue-rotate(270deg) saturate(140%) brightness(120%)' },
  { name: 'Mystic', value: 'brightness(105%) saturate(120%) hue-rotate(45deg)' }
];